### PR TITLE
Add tests and methods for models

### PR DESCRIPTION
**Pull request by faisalakb**
In this project apply the following features :100:  
    
     - Add the following validations: :
        For the User model:
            Name must not be blank.
            PostsCounter must be an integer greater than or equal to zero.
       - For the Post model: :
            Title must not be blank.
            Title must not exceed 250 characters.
            CommentsCounter must be an integer greater than or equal to zero.
            LikesCounter must be an integer greater than or equal to zero.
    - Add unit specs for all of your models' methods and validations. :

### CODE REVIEW

**Review by fobadara — CHANGES_REQUESTED** [review]
Hi @faisalakb, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

REDO

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.

## Required Changes ♻️
_Check the comments under the review._
I had to include some comments here because it could not be done inline
[REQUIRED] Kindly include specs for the recent_comments method in the user model. You are expected to include tests for all custom methods.
[REQUIRED] Kindly include specs for the recent_comments method in the post model. You are expected to include tests for all custom methods.
[REQUIRED] Please add tests for the custom methods in the comments and likes models as it is a requirement for this milestone

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
Please check i address the above issues/

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @faisalakb, 

To highlight 👍🏽 
✔️ Custom methods are tested
✔️ All tests pass
✔️ No errors

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
Thanks for the time

**Pull request merged**
